In [1]:
import numpy as np
import pandas as pd

In [3]:
cardio_cancer_df = pd.read_csv("cardio_cancer_per_county.csv")
resp_df = pd.read_csv("respiratory/respiratory_counties_trends.csv")

In [4]:
cardio_cancer_df.head()

,FIPS,County,cardio_death,total_cancer,bladder,brain,breast,breast_insitu,cervix,colon,...,lung_range,melanoma_range,non-hudgkin lymphoma_range,oral cavity_range,ovay_range,pancreas_range,prostate_range,stomach_range,thyroid_range,uteras_range
0,0,US,216.3,449.4,19.4,6.4,128.1,29.4,7.7,33.0,...,0.3,0.2,0.2,0.1,0.1,0.1,0.5,0.1,0.1,0.3
1,2013,"Aleutians East, Alaska",95.1,142.2,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,2016,"Aleutians West, Alaska",89.8,378.4,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,2020,"Anchorage, Alaska",177.0,440.1,17.9,7.1,134.8,26.3,8.1,35.5,...,10.9,5.8,6.5,3.6,4.7,5.4,17.6,4.9,4.0,8.4
4,2050,"Bethel, Alaska",263.4,397.4,0.0,0.0,51.0,0.0,0.0,79.0,...,0.0,0.0,0.0,0.0,0.0,0.0,110.4,0.0,0.0,0.0

In [5]:
resp_df.head()

,FIPS,State,Total Population,Pediatric Asthma,Adult Asthma,COPD,Adult Chronic Lung Disease,Lung Cancer
0,1001,"Autauga County, Alabama",56145,1718,3906,4274,8657,35
1,1003,"Baldwin County, Alabama",229287,6393,16246,19461,36546,143
2,1005,"Barbour County, Alabama",24589,664,1760,2001,3855,16
3,1007,"Bibb County, Alabama",22136,584,1603,1754,3433,14
4,1009,"Blount County, Alabama",57879,1742,4028,4638,9075,36

In [13]:
cardio_resp_cancer_df = cardio_cancer_df.merge(resp_df,on="FIPS",how="outer")
cardio_resp_cancer_df.head()

,FIPS,County,cardio_death,total_cancer,bladder,brain,breast,breast_insitu,cervix,colon,...,stomach_range,thyroid_range,uteras_range,State,Total Population,Pediatric Asthma,Adult Asthma,COPD,Adult Chronic Lung Disease,Lung Cancer
0,0,US,216.3,449.4,19.4,6.4,128.1,29.4,7.7,33.0,...,0.1,0.1,0.3,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2013,"Aleutians East, Alaska",95.1,142.2,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,"Aleutians East Borough, Alaska",3401.0,18.0,276.0,141.0,382.0,2.0
2,2016,"Aleutians West, Alaska",89.8,378.4,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,"Aleutians West Census Area, Alaska",5680.0,51.0,434.0,209.0,616.0,3.0
3,2020,"Anchorage, Alaska",177.0,440.1,17.9,7.1,134.8,26.3,8.1,35.5,...,4.9,4.0,8.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2050,"Bethel, Alaska",263.4,397.4,0.0,0.0,51.0,0.0,0.0,79.0,...,0.0,0.0,0.0,"Bethel Census Area, Alaska",18437.0,487.0,1063.0,497.0,1865.0,9.0

In [14]:
cardio_resp_cancer_df.isna().sum()

FIPS                            0
County                          0
cardio_death                    2
total_cancer                  254
bladder                       254
brain                         254
breast                        254
breast_insitu                 254
cervix                        254
colon                         254
esophagus                     254
kidney and renal              254
leukemia                      254
liver                         254
lung                          254
melanoma                      254
non-hudgkin lymphoma          254
oral cavity                   254
ovay                          254
pancreas                      254
prostate                      254
stomach                       254
thyroid                       254
uteras                        254
Rate_range                    254
bladder_range                 254
brain_range                   254
breast_range                  254
breast_insitu_range           254
cervix_range                  254
colon_range                   254
esophagus_range               254
kidney and renal_range        254
leukemia_range                254
liver_range                   254
lung_range                    254
melanoma_range                254
non-hudgkin lymphoma_range    254
oral cavity_range             254
ovay_range                    254
pancreas_range                254
prostate_range                254
stomach_range                 254
thyroid_range                 254
uteras_range                  254
State                         277
Total Population              277
Pediatric Asthma              277
Adult Asthma                  277
COPD                          277
Adult Chronic Lung Disease    277
Lung Cancer                   277
dtype: int64

In [15]:
cardio_cancer_df["County"].str.contains("Oklahoma").sum()

77

In [16]:
cardio_resp_cancer_df["County"].str.contains("Oklahoma").sum()

77

In [17]:
cardio_resp_cancer_df.drop(columns=["State"],inplace=True)

In [18]:
cardio_resp_cancer_df.head()

,FIPS,County,cardio_death,total_cancer,bladder,brain,breast,breast_insitu,cervix,colon,...,prostate_range,stomach_range,thyroid_range,uteras_range,Total Population,Pediatric Asthma,Adult Asthma,COPD,Adult Chronic Lung Disease,Lung Cancer
0,0,US,216.3,449.4,19.4,6.4,128.1,29.4,7.7,33.0,...,0.5,0.1,0.1,0.3,NaN,NaN,NaN,NaN,NaN,NaN
1,2013,"Aleutians East, Alaska",95.1,142.2,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,3401.0,18.0,276.0,141.0,382.0,2.0
2,2016,"Aleutians West, Alaska",89.8,378.4,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,5680.0,51.0,434.0,209.0,616.0,3.0
3,2020,"Anchorage, Alaska",177.0,440.1,17.9,7.1,134.8,26.3,8.1,35.5,...,17.6,4.9,4.0,8.4,NaN,NaN,NaN,NaN,NaN,NaN
4,2050,"Bethel, Alaska",263.4,397.4,0.0,0.0,51.0,0.0,0.0,79.0,...,110.4,0.0,0.0,0.0,18437.0,487.0,1063.0,497.0,1865.0,9.0

In [19]:
cardio_resp_cancer_df.to_csv("cardio_cancer_resp.csv",index=False,na_rep="NaN")