In [1]:
import pandas as pd
import numpy as np

In [2]:
states = {"AL":"Alabama","AK":"Alaska","AZ":"Arizona","AR":"Arkansa"
         ,"CA":"California","CO":"Colorado","CT":"Connecticut","DE":"Delaware"
         ,"DC":"District of Columbia","FL":"Folorida","GA":"Georgia","HI":"Hawaii"
         ,"ID":"Idaho","IL":"Illinois","IN":"Indiana","IA":"Iowa","KS":"Kansas"
         ,"KY":"Kentucky","LA":"Louisiana","ME":"Maine","MD":"Maryland"
         ,"MA":"Massachusetts","MI":"Michigan","MN":"Minnesota","MS":"Mississippi"
         ,"MO":"Missouri","MT":"Montana","NE":"Nebraska","NV":"Nevada","NH":"New Hampshire"
         ,"NJ":"New Jersey","NM":"New Mexico","NY":"New York","NC":"North Carolina"
         ,"ND":"North Dakota","OH":"Ohio","OK":"Oklahoma","OR":"Oregon","PA":"Pennsylvania"
         ,"RI":"Rhode Island","SC":"South Carolina","SD":"South Dakota","TN":"Tennessee","TX":"Texas"
         ,"UT":"Utah","VT":"Vermont","VA":"Virginia","WA":"Washington","WV":"West Virginia"
         ,"WI":"Wisconsin","WY":"Wyoming","PR":"Puerto Rico"}

In [3]:
df = pd.DataFrame()

In [4]:
#Note: pandas couldn't read the file if the excel fiel was open!!
# There is no data available for OK
for i in states.keys():
    if i !="OK":
        temp_df = pd.read_excel("trends.xlsx",sheet_name=i)
        temp_df.drop(temp_df.index[0],inplace=True)
        temp_df["State or County"] = temp_df["State or County"].astype(str) + ", "+ str(states[i])
        df = pd.concat([df, temp_df])

In [5]:
df.head()

,State or County,Total Population,Pediatric Asthma,Adult Asthma,COPD,Adult Chronic Lung Disease,Lung Cancer
1,"Autauga County, Alabama",56145,1718,3906,4274,8657,35
2,"Baldwin County, Alabama",229287,6393,16246,19461,36546,143
3,"Barbour County, Alabama",24589,664,1760,2001,3855,16
4,"Bibb County, Alabama",22136,584,1603,1754,3433,14
5,"Blount County, Alabama",57879,1742,4028,4638,9075,36

In [6]:
df.rename(columns={"State or County":"State"},inplace=True)

In [7]:
cancer_df = pd.read_csv("../cancer_dataset/cancer_per_county.csv")
cancer_df.head()

,FIPS,State,Rate,bladder,brain,breast,breast_insitu,cervix,colon,esophagus,...,lung_range,melanoma_range,non-hudgkin lymphoma_range,oral cavity_range,ovay_range,pancreas_range,prostate_range,stomach_range,thyroid_range,uteras_range
0,0,US (SEER+NPCR),449.4,19.4,6.4,128.1,29.4,7.7,33.0,1.8,...,0.3,0.2,0.2,0.1,0.1,0.1,0.5,0.1,0.1,0.3
1,12125,"Union County, Florida",1204.0,42.7,0.0,195.3,0.0,0.0,0.0,0.0,...,75.4,0.0,0.0,0.0,0.0,0.0,92.4,26.7,0.0,0.0
2,19147,"Palo Alto County, Iowa",659.2,27.9,0.0,148.6,0.0,0.0,0.0,0.0,...,63.6,0.0,0.0,0.0,0.0,0.0,100.9,0.0,0.0,0.0
3,31009,"Blaine County, Nebraska",636.7,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,21071,"Floyd County, Kentucky",620.5,19.2,7.2,144.9,25.2,20.3,60.9,0.0,...,39.9,19.6,16.8,0.0,0.0,15.3,38.5,0.0,17.7,22.1

In [8]:
fips_state = cancer_df[["FIPS", "State"]]

In [9]:
fips_state.head()

    FIPS                    State
0      0           US (SEER+NPCR)
1  12125    Union County, Florida
2  19147   Palo Alto County, Iowa
3  31009  Blaine County, Nebraska
4  21071   Floyd County, Kentucky

In [10]:
resp = df.merge(fips_state,on="State")

In [11]:
resp = resp[["FIPS","State","Total Population","Pediatric Asthma","Adult Asthma","COPD","Adult Chronic Lung Disease","Lung Cancer"]]

In [12]:
resp.isna().sum()

FIPS                          0
State                         0
Total Population              0
Pediatric Asthma              0
Adult Asthma                  0
COPD                          0
Adult Chronic Lung Disease    0
Lung Cancer                   0
dtype: int64

In [14]:
resp.head()

,FIPS,State,Total Population,Pediatric Asthma,Adult Asthma,COPD,Adult Chronic Lung Disease,Lung Cancer
0,1001,"Autauga County, Alabama",56145,1718,3906,4274,8657,35
1,1003,"Baldwin County, Alabama",229287,6393,16246,19461,36546,143
2,1005,"Barbour County, Alabama",24589,664,1760,2001,3855,16
3,1007,"Bibb County, Alabama",22136,584,1603,1754,3433,14
4,1009,"Blount County, Alabama",57879,1742,4028,4638,9075,36

In [15]:
resp.to_csv("respiratory_counties_trends.csv",index=False)